// Generated by scripts/generate-supabase-types.mjs
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      bible_books: {
        Row: {
          id: string;
          translation_id: string | null;
          order_index: number;
          name: string;
          abbreviation: string | null;
          chapters: number;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          translation_id?: string | null;
          order_index: number;
          name: string;
          abbreviation?: string | null;
          chapters: number;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          translation_id?: string | null;
          order_index?: number;
          name?: string;
          abbreviation?: string | null;
          chapters?: number;
          created_at?: string | null;
        };
        Relationships: [];
      };

      bible_translations: {
        Row: {
          id: string;
          code: string;
          name: string;
          language: string | null;
          version: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          language?: string | null;
          version?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          language?: string | null;
          version?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };

      scripture_chunks: {
        Row: {
          id: string;
          translation_id: string | null;
          book_id: string | null;
          chapter: number;
          content_json: Json;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter: number;
          content_json: Json;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number;
          content_json?: Json;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };

      user_bookmarks: {
        Row: {
          id: string;
          user_id: string;
          translation_id: string | null;
          book_id: string | null;
          chapter: number | null;
          verse: number | null;
          label: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number | null;
          verse?: number | null;
          label?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number | null;
          verse?: number | null;
          label?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };

      user_highlights: {
        Row: {
          id: string;
          user_id: string;
          translation_id: string | null;
          book_id: string | null;
          chapter: number;
          verse_start: number;
          verse_end: number;
          color: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter: number;
          verse_start: number;
          verse_end: number;
          color?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number;
          verse_start?: number;
          verse_end?: number;
          color?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };

      user_memory_verses: {
        Row: {
          id: string;
          user_id: string;
          translation_id: string | null;
          book_id: string | null;
          chapter: number | null;
          verse_start: number | null;
          verse_end: number | null;
          ease: number | null;
          interval_days: number | null;
          next_review_date: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number | null;
          verse_start?: number | null;
          verse_end?: number | null;
          ease?: number | null;
          interval_days?: number | null;
          next_review_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number | null;
          verse_start?: number | null;
          verse_end?: number | null;
          ease?: number | null;
          interval_days?: number | null;
          next_review_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };

      user_notes: {
        Row: {
          id: string;
          user_id: string;
          translation_id: string | null;
          book_id: string | null;
          chapter: number | null;
          verse_start: number | null;
          verse_end: number | null;
          body: string;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number | null;
          verse_start?: number | null;
          verse_end?: number | null;
          body: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number | null;
          verse_start?: number | null;
          verse_end?: number | null;
          body?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };

      user_progress: {
        Row: {
          id: string;
          user_id: string;
          translation_id: string | null;
          book_id: string | null;
          chapter: number | null;
          progress: number | null;
          completed: boolean | null;
          last_opened: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number | null;
          progress?: number | null;
          completed?: boolean | null;
          last_opened?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          translation_id?: string | null;
          book_id?: string | null;
          chapter?: number | null;
          progress?: number | null;
          completed?: boolean | null;
          last_opened?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: { [key: string]: never };
    Functions: { [key: string]: never };
    Enums: { [key: string]: never };
    CompositeTypes: { [key: string]: never };
  };
};
